title: "Xyrix Service Dashboard Documentation ğŸ–¥ï¸âœ¨"
description: "Official documentation for the Xyrix Service Dashboard."

theme: jekyll-theme-merlot

include:
  - docs

permalink: pretty

navbar:
  - name: "ğŸ  Home"
    link: "/"
  - name: "ğŸ“ Introduction"
    link: "/docs/01_introduction.html"
  - name: "ğŸš€ Getting Started"
    link: "/docs/02_getting_started.html"
  - name: "âš™ï¸ Configuration"
    link: "/docs/03_configuration.html"
  - name: "ğŸŒŸ Features"
    link: "/docs/04_features.html"
  - name: "ğŸ”Œ API Reference"
    link: "/docs/05_api_reference.html"
  - name: "â“ FAQ"
    link: "/docs/06_faq.html"

markdown: kramdown
kramdown:
  input: GFM

google_analytics: ""
